### PR TITLE
fixes #44 - handle no stubs case

### LINKED ISSUE #44: Handle the case of no stubbed_commands
The following fails with "Cannot find /tmp/asdfasdfasdf/*_overrides.sh" because there are no stubbed commands. It works if there are no parameters and/or if any stub is created, regardless of if it's used.

Script under test:
```bash
exit 0
```

Spec:
```ruby
describe 'failing' do
  let(:stubbed_env) {created_stubbed_env}
  it 'will fail' do
    # Add this to see it pass
    # stubbed_env.stub_command(:anything)

    out, err, rv = stubbed_env.execute("path/to/script some_parameter")

    expect(out).to eql ""
    expect(err).to eql ""
    expect(rv.exitstatus).to eql 0
  end 
end
```

### PR DESCRIPTION
**Pull request by bennyhat**
Please try this out on Mac OS X, as it includes some absolute pathing.

### CODE REVIEW

File: bin/function_override_wrapper.sh.erb [hunk 1]
```diff
@@ -10,7 +14,7 @@ done
 command_exit_code=$?
 
 # filter stderr for readonly problems
-grep -v "readonly function" <%=wrapped_error_path_binding_for_template%> >&2
+${system_grep} -v "readonly function" <%=wrapped_error_path_binding_for_template%> >&2
 
 # return original exit code
-exit ${command_exit_code}'
\ No newline at end of file
+exit ${command_exit_code}'
```
Comment (mdurban) [inline bin/function_override_wrapper.sh.erb]: whereis

**Comment by mdurban** [comment]
I thought just using a 'which' would work, but 'wereis' would be better
whereis

**Comment by bennyhat** [comment]
Nice solution!
